# Generated by Django 3.0.6 on 2020-06-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='liked_post',
        ),
        migrations.AddField(
            model_name='like',
            name='n_likes',
            field=models.IntegerField(default=0),
        ),
    ]
