# Generated by Django 3.0.6 on 2020-06-05 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200604_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='n_likes',
        ),
    ]
