# Generated by Django 3.0.6 on 2020-06-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_reply_savedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='created',
        ),
    ]
