# Generated by Django 3.0.6 on 2020-06-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20200622_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='savedpost',
            old_name='timestamp',
            new_name='created',
        ),
    ]
