# Generated by Django 2.2.12 on 2020-05-18 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(upload_to='users/profile_pictures')),
                ('biography', models.TextField(max_length=500)),
                ('website', models.URLField(max_length=70)),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Mujer'), ('female', 'Hombre'), ('other', 'Otro')], max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
