# Generated by Django 2.2.12 on 2020-05-22 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Mujer'), ('female', 'Hombre'), ('other', 'Otro'), ('default', '----')], default='default', max_length=10),
        ),
    ]
