# Generated by Django 3.0.6 on 2020-06-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_time',
            new_name='created',
        ),
    ]
